editAccessOverride = "id_digitiser"
dataUrl = "suivi_chiro/contact_taxon/"
editAccess = 3

subDataUrl = "suivi_chiro/biometries/"
subSchemaUrl = "config?app=suivi_chiro&vue=biometrie&vue=list"
subEditRef = "id"
subEditSchemaUrl = "config?app=suivi_chiro&vue=biometrie&vue=form"
subEditAccess = 3
subSchemaAdd = 3

[[groups]]
    name = "Général"
    glyphicon = "glyphicon-info-sign"

    [[groups.fields]]
        name = "cd_nom"
        type = "num"
        label = "Cd nom"

    [[groups.fields]]
        name = "nom_complet"
        type = "string"
        label = "Nom taxon"

    [[groups.fields]]
        name = "tx_presume"
        type = "string"
        label = "Taxon presumé"

    [[groups.fields]]
        name = "espece_incertaine"
        type = "bool"
        label = "Espece incertaine"

    [[groups.fields]]
        name = "indices"
        thesaurus_code_type = "METH_OBS"
        type = "multisel"
        label = "Indices"

    [[groups.fields]]
        name = "indices_cmt"
        type = "string"
        label = "Description indices"

    [[groups.fields]]
        name = "id_nomenclature_activite"
        thesaurus_code_type = "CHI_ACTIVITE"
        type = "select"
        label = "Statut biologique"

    [[groups.fields]]
        name = "id_nomenclature_eta_bio"
        thesaurus_code_type = "ETA_BIO"
        type = "select"
        label = "Etat biologique"

    [[groups.fields]]
        name = "id_nomenclature_preuve_repro"
        thesaurus_code_type = "CHI_REPRO"
        type = "select"
        label = "Preuves de reproduction"

    # [[groups.fields]]
    #     help = "Photographies pour identification"
    #     name = "obsTaxonFichiers"
    #     type = "file"
    #     label = "Photographies"

    #     [groups.fields.options]
    #         target = "uploads/chiro/obsTaxon/"

[[groups]]
    name = "Détail"
    glyphicon = "glyphicon-search"

    [[groups.fields]]
        name = "denombrements"
        label = "Dénombrement"
        type = "subgroup"

        [[groups.fields.fields]]
            name = "id_nomenclature_life_stage"
            label = "Age"
            thesaurus_code_type = "STADE_VIE"
            type = "select"

        [[groups.fields.fields]]
            name = "id_nomenclature_sex"
            label = "Sexe"
            thesaurus_code_type =  "SEXE"
            type = "select"

        [[groups.fields.fields]]
            name = "count_min"
            label = "Nb min"
            type = "string"

        [[groups.fields.fields]]
            name = "count_max"
            label = "Nb max"
            type = "string"


[[groups]]
    name = "Médias"
    glyphicon = "glyphicon-file"

  [[groups.fields]]
      name = "medium"
      type = "file"
      label = "Fichiers associés"

[[groups]]
    name = "Metadonnées"
    glyphicon = "glyphicon-stats"

    [[groups.fields]]
        name = "id_digitiser"
        type = "xhr"
        label = "Numérisateur"

        [groups.fields.options]
            url = "users/role"
            displayField = ["nom_role", "prenom_role"]

    [[groups.fields]]
        name = "meta_create_date"
        type = "date"
        label = "Création donnée"

    [[groups.fields]]
        name = "meta_update_date"
        type = "date"
        label = "Dernière mise à jour"


