subDataUrl = "suivi_chiro/visites/"
subSchemaUrl = "config?app=suivi_chiro&vue=visite&vue=list"
formUrl = "config?app=suivi_chiro&vue=site&vue=form"
mapSize = "large"
dataUrl = "suivi_chiro/site/"
mapConfig = "static/configs/suivi_chiro/resources/chiro_site.json"
editAccess = 3
mapData = "suivi_chiro/sites"
subEditAccess = 2

[[groups]]
    name = "Informations"
    glyphicon = "glyphicon-info-sign"

    [[groups.fields]]
        name = "base_site_code"
        type = "string"
        label = "Code site"

    [[groups.fields]]
        name = "id_inventor"
        type = "xhr"
        label = "Observateur"

            [groups.fields.options]
                url = "users/role"
                displayField = ["nom_role", "prenom_role"]

    [[groups.fields]]
        help = "Date d'ajout du site à la base de données"
        name = "first_use_date"
        type = "date"
        label = "Date de création"

    [[groups.fields]]
        help = "Type de lieu"
        name = "id_nomenclature_type_site"
        thesaurusID = 116
        type = "select"
        label = "Type"

#   [[groups.fields]]
#       name = "refCommune"
#       type = "xhr"
#       label = "Commune"

#       [groups.fields.options]
#           url = "commune"
#           multi = true

    [[groups.fields]]
        name = "site_actif"
        type = "bool"
        label = "Site actif"


[[groups]]
    name = "Détails"
    glyphicon = "glyphicon-search"

    [[groups.fields]]
        name = "description"
        type = "string"
        label = "Description"

#   [[groups.fields]]
#       name = "siteFichiers"
#       type = "file"
#       label = "Fichiers associés"

#       [groups.fields.options]
#           target = "uploads/chiro/site/"

    [[groups.fields]]
        help = "Fréquentation du site"
        name = "id_nomenclature_frequentation"
        thesaurusID = 500
        type = "select"
        label = "Fréquentation"

    [[groups.fields]]
        help = "Menaces pesant sur le site"
        name = "menaces_ids"
        thesaurusID = 502
        type = "multisel"
        label = "Menaces"

    [[groups.fields]]
        help = "Description des menaces pesant sur le site"
        name = "menace_cmt"
        type = "string"
        label = "Description menaces"

    [[groups.fields]]
        help = "Aménagements effectués sur le site"
        name = "amenagements_ids"
        thesaurusID = 501
        type = "multisel"
        label = "Aménagements"

    [[groups.fields]]
        help = "Actions entreprises pour la préservation du site"
        name = "actions"
        type = "string"
        label = "Actions"


[[groups]]
    name = "Contact"
    glyphicon = "glyphicon-phone-alt"

    [[groups.fields]]
        name = "contact_nom"
        type = "string"
        label = "Nom du contact"

    [[groups.fields]]
        name = "contact_prenom"
        type = "string"
        label = "Prénom du contact"

    [[groups.fields]]
        name = "contact_adresse"
        type = "string"
        label = "Adresse du contact"

    [[groups.fields]]
        name = "contact_code_postal"
        type = "string"
        label = "Code postal"

    [[groups.fields]]
        name = "contact_ville"
        type = "string"
        label = "Ville"

    [[groups.fields]]
        name = "contact_telephone"
        type = "string"
        label = "Téléphone"

    [[groups.fields]]
        name = "contact_portable"
        type = "string"
        label = "Portable"

    [[groups.fields]]
        help = "Informations complémentaires contact"
        name = "contact_commentaire"
        type = "string"
        label = "Commentaires contact"


[[groups]]
    name = "Metadonnées"
    glyphicon = "glyphicon-stats"

    [[groups.fields]]
        name = "id_digitiser"
        type = "xhr"
        label = "Numérisateur"

        [groups.fields.options]
            url = "users/role"
            displayField = ["nom_role", "prenom_role"]

    [[groups.fields]]
        name = "meta_create_date"
        type = "date"
        label = "Création donnée"

    [[groups.fields]]
        name = "meta_update_date"
        type = "date"
        label = "Dernière mise à jour"


[[groups]]
    name = "Médias"
    glyphicon = "glyphicon-file"

  [[groups.fields]]
      name = "medium"
      type = "file"
      label = "Fichiers associés"
