updateSuccessMessage = "Modification réussie"
createSuccessMessage = "Création réussie"
formTitleUpdate = "Modification du site "
editAccess = 5
formDeleteRedirectUrl = "g/chiro/site/list"
formTitleRef = "bsNom"
formCreateCancelUrl = "g/chiro/site/list"
deleteSuccessMessage = "Suppression réussie"
formTitleCreate = "Nouveau site"
deleteAccess = 5

[[groups]]
    name = "Localisation"

    [[groups.fields]]
        name = "geom"
        type = "geom"
        label = "Coordonnées GPS"

        [groups.fields.options]
            geometryType = "point"
            dataUrl = "chiro/site"
            mapConfig = "static/configs/suivi_chiro/resources/chiro_site.json"
            mapData = "suivi_chiro/sites"

[[groups]]
    name = "Informations"

    [[groups.fields]]
        name = "id_site_infos"
        type = "hidden"
        label = "ID"

    [[groups.fields]]
        name = "id_base_site"
        type = "hidden"
        label = "ID"

    [[groups.fields]]
        name = "id"
        type = "hidden"
        label = "ID"

    [[groups.fields]]
        name = "uuid_base_site"
        type = "hidden"
        label = "uuid_base_site"

    [[groups.fields]]
        name = "id_digitiser"
        type = "hidden"
        label = "Numerisateur"

        [groups.fields.options]
            ref = "userId"

    [[groups.fields]]
        help = "nom du site"
        name = "base_site_name"
        type = "string"
        label = "Nom"

        [groups.fields.options]
            minLength = 5
            maxLength = 250

    [[groups.fields]]
        thesaurusID = 116
        #thesaurusHierarchyID = "012.001"
        #default = 37
        label = "Type"
        help = "Type de lieu"
        type = "select"
        name = "id_nomenclature_type_site"

    [[groups.fields]]
        name = "id_inventor"
        type = "xhr"
        label = "Observateur"

        [groups.fields.options]
            url = "users/menu/10"
            required = true
            reverseurl = "users/role"
            displayField = ["nom_role", "prenom_role"]
            idField = "id_role"
            searchField = "nom_complet"

    [[groups.fields]]
        help = "date d'ajout à la base de données"
        name = "first_use_date"
        type = "date"
        label = "Date créa."

        [groups.fields.options]
            required = true

    [[groups.fields]]
        help = "Détermine si le suivi du site est définitivement abandonné"
        name = "site_actif"
        default = true
        type = "bool"
        label = "Site actif"

    [[groups.fields]]
        name = "description"
        type = "text"
        label = "Description"

        [groups.fields.options]
            maxLength = 1000

[[groups]]
    name = "Etat"

    [[groups.fields]]
        help = "Type de menace pesant sur le site"
        name = "menaces_ids"
        thesaurusID = 502
        type = "multisel"
        label = "Types de menace"

    [[groups.fields]]
        help = "Type de menace pesant sur le site"
        name = "amenagements_ids"
        thesaurusID = 501
        type = "multisel"
        label = "Types d'aménagements"

    [[groups.fields]]
        help = "Informations complémentaires sur les menaces pesant sur le site"
        name = "menace_cmt"
        type = "text"
        label = "Informations menaces"

    [[groups.fields]]
        thesaurusID = 500
        default = 0
        label = "Fréquentation"
        help = "Estimation de la fréquentation du site"
        type = "select"
        name = "id_nomenclature_frequentation"

        [groups.fields.options]
            nullable = true

    [[groups.fields]]
        help = "Actions entreprises pour la préservation du site"
        name = "actions"
        type = "text"
        label = "Actions"

[[groups]]
    name = "Contact"

    [[groups.fields]]
        name = "contact_nom"
        type = "string"
        label = "Nom du contact"

        [groups.fields.options]
            maxLength = 25

    [[groups.fields]]
        name = "contact_prenom"
        type = "string"
        label = "Prénom du contact"

        [groups.fields.options]
            maxLength = 25

    [[groups.fields]]
        name = "contact_adresse"
        type = "string"
        label = "Adresse du contact"

        [groups.fields.options]
            maxLength = 150

    [[groups.fields]]
        name = "contact_code_postal"
        type = "string"
        label = "Code postal"

        [groups.fields.options]
            maxLength = 5

    [[groups.fields]]
        name = "contact_ville"
        type = "string"
        label = "Ville"

        [groups.fields.options]
            maxLength = 100

    [[groups.fields]]
        name = "contact_telephone"
        type = "string"
        label = "Téléphone"

        [groups.fields.options]
            maxLength = 15

    [[groups.fields]]
        name = "contact_portable"
        type = "string"
        label = "Portable"

        [groups.fields.options]
            maxLength = 15

    [[groups.fields]]
        name = "contact_commentaire"
        type = "text"
        label = "Commentaires contact"

        [groups.fields.options]
            maxLength = 1000


[[groups]]
    name = "Fichiers"

    [[groups.fields]]
        help = "Fichiers associés"
        name = "medium"
        type = "file"
        label = "Photographies"

        [groups.fields.options]
            maxSize = 2048000
            # accepted = [ "png", "jpg",]
            attachedUUID = "uuid_base_site"
            id_table_location = 6
            url_nomenclature_media_type = "nomenclatures/nomenclature/117"
