emptyMsg = "Aucun site pour le moment"
createUrl = "#/suivi_chiro/edit/site/"
detailUrl = "#/suivi_chiro/site/"
mapSize = "large"
dataUrl = "genericview/monitoring_chiro/v_sites_chiro?geometry_field=geom"
mapConfig = "static/configs/suivi_chiro/resources/chiro_site.json"
editAccess = 5
createBtnLabel = "Nouveau site"
editUrl = "#/suivi_chiro/edit/site/"
title = "Sites"
[[fields]]
    label = "ID"
    type = "text"
    name = "id_base_site"
    [fields.filter]
        id_base_site = "text"
    [fields.options]
        visible = false
[[fields]]
    label = "Nom"
    type = "text"
    name = "base_site_name"
    [fields.filter]
        base_site_name = "text"
    [fields.options]
        visible = true
        style = "xl"
        primary = true
[[fields]]
    label = "Code site"
    type = "text"
    name = "base_site_code"
    [fields.filter]
        base_site_code = "text"
    [fields.options]
        visible = false
        style = "xl"
[[fields]]
    name = "nomObservateur"
    type = "text"
    label = "Observateur"
    [fields.filter]
        nomObservateur = "text"
    [fields.option]
        visible = true
        style = "xl"
[[fields]]
    label = "Date créa."
    type = "date"
    name = "first_use_date"
    [fields.filter]
        first_use_date = "text"
    [fields.options]
        visible = false
        type = "date"
        style = "l"
[[fields]]
    label = "Dern. obs."
    type = "date"
    name = "dern_obs"
    [fields.filter]
        dern_obs = "text"
    [fields.options]
        visible = true
        type = "date"
        style = "xs"
[[fields]]
    label = "Nb visites"
    type = "text"
    name = "nb_obs"
    [fields.filter]
        nb_obs = "text"
    [fields.options]
        visible = true
        style = "xs"
[[fields]]
    thesaurusID = 116
    default = 0
    label = "Type"
    type = "select"
    name = "id_nomenclature_type_site"
    [fields.filter]
        id_nomenclature_type_site = "select"
    [fields.options]
        visible = true
        type = "select"
        nullable = true
        style = "l"
[[fields]]
    name = "site_actif"
    type = "bool"
    label = "Site actif"
    [fields.options]
        visible = false
        type = "bool"
        style = "l"

[filtering]
    limit = 2000
    [[filtering.fields]]
        name = "dern_obs"
        type = "date"
        label = "Dernière observation"

    [[filtering.fields]]
        name = "nb_obs"
        type = "num"
        label = "Nombre d'observations"

    [[filtering.fields]]
        thesaurusID = 116
        zeroNull = true
        default = 0
        label = "Type de site"
        type = "select"
        name = "id_nomenclature_type_site"

    [[filtering.fields]]
        name = "first_use_date"
        type = "date"
        label = "Création du site"

