editAccess = 3
[[groups]]
    name = "Général"
    [[groups.fields]]
        name = "id_nomenclature_life_stage"
        thesaurus_code_type = "STADE_VIE"
        type = "select"
        label = "Âge"
        regne = "Animalia"
        group2_inpn = "Mammifères"

    [[groups.fields]]
        name = "id_nomenclature_sex"
        thesaurus_code_type =  "SEXE"
        type = "select"
        label = "Sexe"
        regne = "Animalia"
        group2_inpn = "Mammifères"

    [[groups.fields]]
        name = "poids"
        type = "num"
        label = "Poids (g)"

    [[groups.fields]]
        name = "commentaire"
        type = "string"
        label = "Commentaires"


[[groups]]
    name = "Membre"
    [[groups.fields]]
        name = "ab"
        type = "num"
        label = "AB (mm)"

    [[groups.fields]]
        help = "Mesure du 3ème doigt, métacarpe + 1ère phalange"
        name = "d3mf1"
        type = "num"
        label = "D3MF1 (mm)"

    [[groups.fields]]
        help = "Mesure du 3ème doigt, 2ème et 3ème phalanges"
        name = "d3f2f3"
        type = "num"
        label = "D3F2F3 (mm)"

    [[groups.fields]]
        help = "Longueur totale du 3ème doigt"
        name = "d3total"
        type = "num"
        label = "D3 total (mm)"

    [[groups.fields]]
        help = "Mesure du 5ème doigt"
        name = "d5"
        type = "num"
        label = "D5 (mm)"


[[groups]]
    name = "Crane"
    [[groups.fields]]
        help = "Mesure canine - 3ème molaire (mandibule supérieure)"
        name = "cm3sup"
        type = "num"
        label = "CM3SUP (mm)"

    [[groups.fields]]
        help = "Mesure canine - 3ème molaire (mandibule inférieure)"
        name = "cm3inf"
        type = "num"
        label = "CM3INF (mm)"

    [[groups.fields]]
        help = "Mesure condylobasale"
        name = "cb"
        type = "num"
        label = "CB (mm)"

    [[groups.fields]]
        help = "Mesure mandibule inférieure"
        name = "lm"
        type = "num"
        label = "LM (mm)"

    [[groups.fields]]
        help = "Mesure de l'oreille"
        name = "oreille"
        type = "num"
        label = "Oreille (mm)"


[[groups]]
    name = "Metadonnées"
    glyphicon = "glyphicon-stats"

    [[groups.fields]]
        name = "id_digitiser"
        type = "xhr"
        label = "Numérisateur"

        [groups.fields.options]
            url = "users/role"
            displayField = ["nom_role", "prenom_role"]

    [[groups.fields]]
        name = "metaCreateTimestamp"
        type = "date"
        label = "Création donnée"

    [[groups.fields]]
        name = "metaUpdateTimestamp"
        type = "date"
        label = "Dernière mise à jour"


