editAccess = 3
deleteAccess = 3
[[groups]]
    name = "Général"
    [[groups.fields]]
    name = "id_biometrie"
    type = "hidden"

    [[groups.fields]]
    name = "id_contact_taxon"
    type = "hidden"

    [[groups.fields]]
    name = "id_nomenclature_life_stage"
    thesaurusID = 10
    type = "select"
    label = "Âge"

    [[groups.fields]]
    name = "id_nomenclature_sex"
    thesaurusID = 9
    type = "select"
    label = "Sexe"

    [[groups.fields]]
    name = "id_digitiser"
    type = "hidden"
    label = "Numerisateur"

        [groups.fields.options]
        ref = "userId"

    [[groups.fields]]
    name = "poids"
    type = "num"
    label = "Poids (g)"
        [groups.fields.options]
        step = 0.1
        min = 0

    [[groups.fields]]
    name = "commentaire"
    type = "text"
    label = "Commentaires"


[[groups]]
    name = "Membre"
    [[groups.fields]]
    name = "ab"
    type = "num"
    label = "AB (mm)"

    [[groups.fields]]
    help = "Mesure du 3ème doigt, métacarpe + 1ère phalange"
    name = "d3mf1"
    type = "num"
    label = "D3MF1 (mm)"

        [groups.fields.options]
        step = 0.1
        min = 0

    [[groups.fields]]
    help = "Mesure du 3ème doigt, 2ème et 3ème phalanges"
    name = "d3f2f3"
    type = "num"
    label = "D3F2F3 (mm)"

        [groups.fields.options]
        step = 0.1
        min = 0

    [[groups.fields]]
    help = "Longueur totale du 3ème doigt"
    name = "d3total"
    type = "num"
    label = "D3 total (mm)"

        [groups.fields.options]
        step = 0.1
        min = 0

    [[groups.fields]]
    help = "Mesure du 5ème doigt"
    name = "d5"
    type = "num"
    label = "D5 (mm)"

        [groups.fields.options]
        step = 0.1
        min = 0

[[groups]]
name = "Crane"
    [[groups.fields]]
    help = "Mesure canine - 3ème molaire (mandibule supérieure)"
    name = "cm3sup"
    type = "num"
    label = "CM3SUP (mm)"

        [groups.fields.options]
        step = 0.1
        min = 0
    [[groups.fields]]
    help = "Mesure canine - 3ème molaire (mandibule inférieure)"
    name = "cm3inf"
    type = "num"
    label = "CM3INF (mm)"

        [groups.fields.options]
        step = 0.1
        min = 0
    [[groups.fields]]
    help = "Mesure condylobasale"
    name = "cb"
    type = "num"
    label = "CB (mm)"

        [groups.fields.options]
        step = 0.1
        min = 0

    [[groups.fields]]
    help = "Mesure mandibule inférieure"
    name = "lm"
    type = "num"
    label = "LM (mm)"

        [groups.fields.options]
        step = 0.1
        min = 0

    [[groups.fields]]
    help = "Mesure de l'oreille"
    name = "oreille"
    type = "num"
    label = "Oreille (mm)"

        [groups.fields.options]
        step = 0.1
        min = 0

