[[fields]]
name = "cbioAgeId"
thesaurusID = 1
type = "select"
label = "Âge"

[fields.options]
required = true
[[fields]]
name = "metaNumerisateurId"
type = "hidden"
label = "Numerisateur"

[fields.options]
ref = "userId"
[[fields]]
name = "cbioSexeId"
thesaurusID = 2
type = "select"
label = "Sexe"

[fields.options]
required = true
[[fields]]
name = "cbioPoids"
type = "num"
label = "Poids (g)"

[fields.options]
step = 0.1
min = 0
[[fields]]
name = "cbioAb"
type = "num"
label = "AB (mm)"

[fields.options]
step = 0.1
min = 0
[[fields]]
name = "cbioD3mf1"
type = "num"
label = "D3MF1 (mm)"

[fields.options]
step = 0.1
min = 0
[[fields]]
name = "cbioD3f2f3"
type = "num"
label = "D3F2F3 (mm)"

[fields.options]
step = 0.1
min = 0
[[fields]]
name = "cbioD3total"
type = "num"
label = "D3 total (mm)"

[fields.options]
step = 0.1
min = 0
[[fields]]
name = "cbioD5"
type = "num"
label = "D5 (mm)"

[fields.options]
step = 0.1
min = 0
[[fields]]
name = "cbioCm3sup"
type = "num"
label = "CM3SUP (mm)"

[fields.options]
step = 0.1
min = 0
[[fields]]
name = "cbioCm3inf"
type = "num"
label = "CM3INF (mm)"

[fields.options]
step = 0.1
min = 0
[[fields]]
name = "cbioCb"
type = "num"
label = "CB (mm)"

[fields.options]
step = 0.1
min = 0
[[fields]]
name = "cbioLm"
type = "num"
label = "LM (mm)"

[fields.options]
step = 0.1
min = 0
[[fields]]
name = "cbioOreille"
type = "num"
label = "Oreille (mm)"

[fields.options]
step = 0.1
min = 0
