emptyMsg = "Aucune biométrie"
createUrl = "suivi_chiro/edit/biometrie/taxon/"
detailUrl = "suivi_chiro/biometrie/"
editAccess = 3
createBtnLabel = "Nouvelle biométrie"
editUrl = "suivi_chiro/edit/biometrie/"
title = "Biométries"
[[fields]]
    label = "Id"
    type = "num"
    name = "id_biometrie"
    [fields.filter]
        id_biometrie = "text"
    [fields.options]
        visible = false
        style = "xl"

[[fields]]
    thesaurus_code_type = "STADE_VIE"
    label = "Âge"
    name = "id_nomenclature_life_stage"
    type = "select"
    [fields.filter]
        id_nomenclature_life_stage = "text"
    [fields.options]
        visible = true
        type = "select"
        primary = true
        style = "xl"

[[fields]]
    thesaurus_code_type =  "SEXE"
    label = "Sexe"
    name = "id_nomenclature_sex"
    type = "select"
    [fields.filter]
        id_nomenclature_sex = "text"
    [fields.options]
        visible = true
        type = "select"
        style = "s"

[[fields]]
    label = "Poids"
    type = "num"
    name = "poids"
    [fields.filter]
        poids = "text"
    [fields.options]
        visible = true
        style = "xs"
