[[fields]]
        name = "id"
        type = "hidden"

[[fields]]
    name = "id_base_visit"
    type = "hidden"
    [fields.options]
        ref = "parent"

[[fields]]
    name = "id_digitiser"
    type = "hidden"
    label = "Numerisateur"
    [fields.options]
        ref = "userId"

[[fields]]
    name = "cd_nom"
    type = "taxhub"
    label = "Nom taxon"
    [fields.options]
        required = true
        id_liste = 1000001

[[fields]]
    name = "tx_presume"
    type = "string"
    label = "Taxon initial"

[[fields]]
    name = "espece_incertaine"
    type = "bool"
    label = "Espece incertaine"

[[fields]]
    thesaurusID = 13
    label = "Activité"
    name = "id_nomenclature_activite"
    type = "select"
    regne = "Animalia"
    group2_inpn = "Mammifères"
    [fields.options]
        nullable = true

[[fields]]
    thesaurusID = 13
    default = 0
    label = "Preuves de reproduction"
    name = "id_nomenclature_preuve_repro"
    type = "select"
    regne = "Animalia"
    group2_inpn = "Mammifères"
    [fields.options]
        nullable = true

[[fields]]
    label = "Indeterminés"
    name = "denombrement.indetermine_indetermine"
    type = "num"
    [fields.options]
        min = 0

[[fields]]
    label = "Femelles adultes"
    name = "denombrement.femelle_adulte"
    type = "num"
    [fields.options]
        min = 0

[[fields]]
    label = "Mâles adultes"
    name = "denombrement.male_adulte"
    type = "num"
    [fields.options]
        min = 0

[[fields]]
    label = "Femelles indeterminés"
    name = "denombrement.femelle_indetermine"
    type = "num"
    [fields.options]
        min = 0

[[fields]]
    label = "Mâles indeterminés"
    name = "denombrement.male_indetermine"
    type = "num"
    [fields.options]
        min = 0


[[fields]]
    label = "Indeterminés juvéniles"
    name = "denombrement.indetermine_juvenile"
    type = "num"
    [fields.options]
        min = 0

[[fields]]
    label = "Indeterminés adultes"
    name = "denombrement.indetermine_adulte"
    type = "num"
    [fields.options]
        min = 0

[[fields]]
    label = "Mâles juveniles"
    name = "denombrement.male_juvenile"
    type = "num"
    [fields.options]
        min = 0

[[fields]]
    label = "Femelles juveniles"
    name = "denombrement.femelle_juvenile"
    type = "num"
    [fields.options]
        min = 0
