editAccessOverride = "id_digitiser"
deleteAccessOverride = "id_digitiser"
deleteAccess = 5
subDataRef = "__biometries__"
dataUrl = "chiro/obs_taxon/"
editAccess = 3
subSchemaUrl = "config?app=suivi_chiro&vue=biometrie&vue=form_many"
subTitle = "Ajout rapide de biometries"
subSchemaAdd = 3
[[groups]]
name = "Informations"
    [[groups.fields]]
        name = "id"
        type = "hidden"

    [[groups.fields]]
        name = "id_base_visit"
        type = "hidden"
        [groups.fields.options]
            ref = "parent"

    [[groups.fields]]
        name = "id_digitiser"
        type = "hidden"
        label = "Numerisateur"
        [groups.fields.options]
            ref = "userId"

    [[groups.fields]]
        name = "cd_nom"
        type = "taxhub"
        label = "Nom taxon"

    [[groups.fields]]
        name = "tx_presume"
        type = "string"
        label = "Taxon présumé"

    [[groups.fields]]
        name = "indices"
        thesaurusID = 14
        type = "multisel"
        label = "Indices"

    [[groups.fields]]
        name = "indices_cmt"
        type = "text"
        label = "Description indices"

    [[groups.fields]]
        thesaurusID = 13
        label = "Activité"
        name = "id_nomenclature_activite"
        type = "select"

        [groups.fields.options]
            nullable = true

    [[groups.fields]]
        thesaurusID = 13
        default = 0
        label = "Preuves de reproduction"
        name = "id_nomenclature_preuve_repro"
        type = "select"
        [groups.fields.options]
            nullable = true

    [[groups.fields]]
        name = "espece_incertaine"
        type = "bool"
        label = "Espece incertaine"

    [[groups.fields]]
        help = "Informations complémentaires sur l'observation"
        name = "commentaire"
        type = "text"
        label = "Commentaires"

    [[groups.fields]]
        help = "Photographies pour identification"
        name = "obsTaxonFichiers"
        type = "file"
        label = "Photographies"

        [groups.fields.options]
            maxSize = 2048000
            accepted = [ "png", "jpg",]
            target = "chiro/obsTaxon"

[[groups]]
    name = "Dénombrement"

    [[groups.fields]]
        name = "denombrements"
        label = "Dénombrement"
        type = "subform"

        [[groups.fields.fields]]
            name = "id_nomenclature_life_stage"
            label = "Age"
            thesaurusID = 10
            type = "select"

        [[groups.fields.fields]]
            name = "id_nomenclature_sex"
            label = "Sexe"
            thesaurusID = 9
            type = "select"

        [[groups.fields.fields]]
            name = "count_min"
            label = "Nb min"
            type = "string"

        [[groups.fields.fields]]
            name = "count_max"
            label = "Nb max"
            type = "string"
