editAccessOverride = "id_digitiser"
subDataUrl = "suivi_chiro/contact_taxons/"
subSchemaUrl = "config?app=suivi_chiro&vue=obs_taxon&vue=list"
subEditRef = "id"
editAccess = 3
subEditSchemaUrl = "config?app=suivi_chiro&vue=obs_taxon&vue=form_many"
subEditAccess = 2
subEditSaveUrl = "suivi_chiro/obs_taxon/many"
subSchemaAdd = 2

[[groups]]
name = "Observation"
glyphicon = "glyphicon-info-sign"
    [[groups.fields]]
        name = "id_base_site"
        type = "xhr"
        label = "Site"
        [groups.fields.options]
            url = "gn_monitoring/siteslist"
            displayField = ["base_site_name"]

    # [[groups.fields]]
    # name = "refCommune"
    # type = "xhr"
    # label = "Commune"

    #     [groups.fields.options]
    #     url = "commune"
    #     multi = true

    [[groups.fields]]
    name = "visit_date"
    type = "date"
    label = "Date"

    [[groups.fields]]
        name = "observers"
        type = "xhr"
        label = "Observateurs"
       [groups.fields.options]
            url = "users/role"
            displayField = ["nom_role", "prenom_role"]

    [[groups.fields]]
    name = "id_nomenclature_mod_id"
    thesaurusID = 115
    type = "select"
    label = "Mode d'observation"

    [[groups.fields]]
    name = "comments"
    type = "string"
    label = "Commentaires"

    [[groups.fields]]
    name = "temperature"
    type = "string"
    label = "Température (°C)"

    [[groups.fields]]
    name = "humidite"
    type = "string"
    label = "Humidité (%)"


[[groups]]
name = "Metadonnées"
glyphicon = "glyphicon-stats"
    [[groups.fields]]
    name = "id_digitiser"
    type = "xhr"
    label = "Numérisateur"

        [groups.fields.options]
        url = "users/role"
            displayField = ["nom_role", "prenom_role"]

    [[groups.fields]]
    name = "meta_create_date"
    type = "date"
    label = "Création donnée"

    [[groups.fields]]
    name = "meta_update_date"
    type = "date"
    label = "Dernière mise à jour"


